### ISSUE TITLE
[WAS] hikariCP config 1차 조정

### ISSUE THREAD

**Issue by belljun3395** [few-letter/few-be#376]
[레포지토리 이전작업] 원본이슈: https://github.com/YAPP-Github/24th-Web-Team-1-BE/issues/89 

 - as-is: 기본값
minimum-idle: 10 (기본값)
maximum-pool-size: 10 (기본값)
idle-timeout: 600000 (10분, 기본값)
max-lifetime: 1800000 (30분, 기본값)
connection-timeout: 30000 (30초, 기본값)
validation-timeout: 5000 (5초, 기본값)

```yml
    hikari:
      pool-name: HikariCP
      minimum-idle: 4
      maximum-pool-size: 16
      connection-timeout: 30000  # 30 seconds
      idle-timeout: 300000  # 5 minutes
      max-lifetime: 1800000  # 30 minutes
      connection-test-query: SELECT 1
```
